[package]
name = "lsm-tree"
version = "0.1.0"
edition = "2021"
rust-version = "1.81.0"

[dependencies]
libc = "0.2.169"
page_size = "0.6.0"
tokio = { version = "1", features = ["full"] }
sysinfo = "0.29"
rand = "0.8"
once_cell = "1.8"



